services:
  ui:
    container_name: ui_dev
    build:
      context: ./
      dockerfile: ui/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./ui:/app
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm start
    env_file:
      - .env

  api:
    container_name: api_dev
    build:
      context: ./
      dockerfile: api/Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - ./api:/app
    command: >
      sh -c "npm install && npx nodemon server.js"
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:

    
      - /db/data/pg:/var/lib/postgresql/data
    env_file:
      - .env