services:
  ui:
    container_name: ui_wrdip_prod
    build:
      context: ui
      dockerfile: Dockerfile.prod
    ports:
      - 80:3000
    command: "npm start"
  
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db