services:
  ui:
    container_name: ui_wrdip_prod
    build:
      context: ui
      dockerfile: Dockerfile.prod
    ports:
      - 80:3000
    command: "npm start"
  
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - /db/data/pg:/var/lib/postgresql/data
    env_file:
      - .env